# Dependencies
markdown:         redcarpet
highlighter:      pygments

analytics :
  provider : google
  google :
      tracking_id : 'UA-59325020-1'
  getclicky :
    site_id :

# Permalinks
permalink:        pretty

# Setup
title:            Sa√∫l Molinero
tagline:          ''
description:      'I usually talk about android development'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Saul M.'
  url:            https://plus.google.com/+SaulMolineroMalvido/posts

disqus_shortname: saulmm

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/saulmm/saulmm.github.com

twitter: '@_saulmm'
